version: 2
jobs:
  build:
    docker:
       - image: ubuntu:18.04
    steps:
      - run:
          name: Update package list
          command: apt-get -y update
      - run:
          name: Install git
          command: apt-get install -y git
      - checkout
      - add_ssh_keys
      - run:
          name: Install system packages
          command: apt install -y build-essential libgsl-dev graphviz plantuml ruby ruby-dev ruby-bundler ruby-fast-stemmer ruby-posix-spawn ruby-rmagick libmagickwand-dev imagemagick
      - run:
          name: Install dependencies
          command: JEYKLL_ENV=prod bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run:
          name: Build website
          command: JEYKLL_ENV=prod bundle exec jekyll build
  deploy:
    docker:
       - image: ubuntu:18.04
    steps:
      - run:
          name: Deploy
          command: ./.deploy.sh
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          context: pasztor.at
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
