version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.4.1-node-browsers
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: Install dependencies
          command: JEYKLL_ENV=prod bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run:
          name: Build website
          command: JEYKLL_ENV=prod bundle exec jekyll build
  deploy:
    docker:
       - image: circleci/ruby:2.4.1-node-browsers
    steps:
      - run:
          name: Deploy
          command: ./.deploy.sh
